---
title: "Practice Task 1"
author: "Richard"
date: "2023-03-20"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Problem 1}
# required packages
# library(readr)
# library(tidyr)
# library(dplyr)

pacman::p_load(dplyr,readr,tidyr,readxl,ggplot2,skimr,gtExtras,ggfortify)

# dt <- readxl::read_excel("refine_original_toy_data.xlsx")[1]
# dt <- dt[,1] %>%
# separate(sep = ",")

dt <- read_csv("refine_original_toy_data.csv")
unique(dt)

```

```{r Problem 2}

dt <- dt %>%
    mutate(company = ifelse(grepl("^phil|^fil|^phl", company,
        ignore.case = TRUE), "philips", company)) %>%
    mutate(company = ifelse(grepl("^ak", company, ignore.case = TRUE),
        "akzo", company)) %>%
    mutate(company = ifelse(grepl("^van", company, ignore.case = TRUE),
        "van_houten", company)) %>%
    mutate(company = ifelse(grepl("^uni", company, ignore.case = TRUE),
        "unilever", company))

```

```{r Problem 3}

dt <- dt %>%
    separate(`Product code / number`, into = c("product_code",
        "Product_number"), sep = "-")
```

```{r Problem 4}
dt <- dt %>%
    mutate(product_category = ifelse(product_code == "p", "Smartphone",
        "")) %>%
    mutate(product_category = ifelse(product_code == "x", "Laptop",
        product_category)) %>%
    mutate(product_category = ifelse(product_code == "v", "TV",
        product_category)) %>%
    mutate(product_category = ifelse(product_code == "q", "Tablet",
        product_category))
```

```{r Problem 5}
dt <- dt %>%
    unite(full_address, c(address, city, country), sep = ",")
```

```{r Problem 6}
dt <- dt %>%
    mutate(company_philips = ifelse(company == "philips", 1,
        0)) %>%
    mutate(company_akzo = ifelse(company == "akzo", 1, 0)) %>%
    mutate(company_van_houten = ifelse(company == "van_houten",
        1, 0)) %>%
    mutate(company_unilever = ifelse(company == "unilever", 1,
        0))
```

```{r Problem 7}
dt <- dt %>%
    mutate(product_smartphone = ifelse(product_category == "Smartphone",
        1, 0)) %>%
    mutate(product_TV = ifelse(product_category == "TV", 1, 0)) %>%
    mutate(product_laptop = ifelse(product_category == "Laptop",
        1, 0)) %>%
    mutate(product_tablet = ifelse(product_category == "Tablet",
        1, 0))
View(dt)
```

```{r Working with Data}
# ---------------Working with Data---------------------

# install th read r package
# install.packages(readr)
# load the read r package
library(readr)
# read csv file using read.table()
df1 <- read_csv("demo csv data.csv", show_col_types = FALSE)
# df1 <- read_csv("data/demo csv data.csv", show_col_types = FALSE)
# read txt file that doesnot headers
library(dplyr)
df2 <- read_delim("demo data text.txt")
# df2 <- read_delim("data/demo data text.txt")
# Or use
df3 <- read_tsv("demo data text.txt") 
View(df3)

# df3 <- read_tsv("data/demo data text.txt")

# utils:: Package

#Importing an Excel file
# install package
install.packages("readxl")
# load package
library(readxl)
# by default, it loads the first sheet
excel_data <- read_excel("demo excel data.xlsx") 
View(excel_data)
# excel_data <- read_excel("data/demo excel data.xlsx")
# if the excel workbook has many sheets and you want to
# load a specific one, e,g, sheet two
excel_data <- read_excel("demo excel data.xlsx", sheet = 1)

#Importing a Stata file
install.packages("readstata13")
library(readstata13)
stata_data <- read.dta13("demo stata data.dta", generate.factors = TRUE)
View(stata_data)
# stata_data <- read.dta13("data/demo stata data.dta", generate.factors = TRUE)

#Importing an R data file
load("demo R data.rda")

#Inbuilt Data sets
# Loading
data(mtcars)
# learn more about the data
`?`(mtcars)
# OR
help(mtcars)
# list available datasets in ggplot2 package
pacman::p_load(ggplot2)
data(package = "ggplot2")

# For a better visual display of the results, additional packages can be used such as skimr, gtsummary, kable, 
install.packages("skimr")
library(skimr)
# get the summary of all the variable, alternative to str()
View(iris)
skim(iris)

sales_report <- readr::read_csv("sales_data.csv")
sales_report

skim(sales_report)

write.csv(sales_report, file = "C:/Users/RichardLubega/Downloads/R Projects/Exported Files/my_data.csv")  # exporting csv data file

```

```{r Task 1}
summary(sales_report)

# ------------------------Task 1---------------------------------------
  
# Load a new data file named “customer_data.xlsx” into RStudio.
excel_file <- readxl::read_xlsx("demo excel data.xlsx")
skim(excel_file)

head(excel_file, n=13)
?tibble
tail(excel_file)

str(excel_file)

summary(excel_file)

pacman::p_load(writexl)
writexl::write_xlsx()

# writexl::write_xlsx(excel_file, path ="C:/Users/RichardLubega/Downloads/R Projects/Exported Files/my_data.xlsx")

writexl::write_xlsx(excel_file,path = "my_data.xlsx")

# writexl::write_xlsx(data_object, file = "my_data.rda") #exporting excel data file

```

```{r Task 2}

# -------------------Task 2----------------------

data(iris)
?iris
flower_data <- iris
# Using the “plot” function, create a scatter plot of the “Sepal.Length” and “Sepal.Width” columns in the “iris” object.
plot(x= flower_data$Sepal.Length, y=flower_data$Sepal.Width)

# Using the “box plot” function, create a box plot of the “Petal.Length” column in the “iris” object, grouped by the “Species” column.
boxplot(flower_data$Petal.Length,flower_data$Species)
library(dplyr)
boxplot(x = flower_data$Sepal.Length)

library(ggplot2)

flower_data %>% 
  ggplot()+ aes(x = Species, y = Sepal.Length)+
  geom_boxplot()

plot()

?boxplot

# Using the “hist” function, create a histogram of the “Petal.Width” column in the “iris” object, grouped by the “Species” column.
group_by(flower_data)=flower_data$Species
hist(x= flower_data$Petal.Width)

# Using the “plot” function, create a line plot of the “Sepal.Length” column in the “iris” object, grouped by the “Species” column.

```

```{r Data Wrangling Packages, echo=TRUE}

# --------------------Data Wrangling-----------------------

# A data set from the ggplot2 package called msleep.
data_set1 <- msleep

skimr::skim(data_set1)

?msleep
data()
data(package="ggplot2")

glimpse(data_set1)
summary(data_set1)

#Filtering Rows
filter(data_set1,data_set1$order == "Primates")

data_set1 %>% 
  filter(data_set1$order =="Primates")
data_set1 %>%
  filter(order == "Primates" & sleep_total > 10)

# Filtering Columns
data_set1 %>%
    filter(order == "Primates", sleep_total > 10) %>%
    select(name, sleep_total, sleep_rem, sleep_cycle)

data_set1 %>% #Renaming columns
    filter(order == "Primates", sleep_total > 10) %>%
    select(name, total = sleep_total, rem = sleep_rem, cycle = sleep_cycle)

data_set1 %>%
    filter(order == "Primates", sleep_total > 10) %>%
    rename(total = sleep_total, rem = sleep_rem, cycle = sleep_cycle)

# Reordering Columns
data_set1 %>%
    filter(order == "Primates", sleep_total > 10) %>%
    select(name, sleep_rem, sleep_cycle, sleep_total)

# Reordering Rows
data_set1 %>%
    filter(order == "Primates", sleep_total > 10) %>%
    select(name, sleep_rem, sleep_cycle, sleep_total) %>%
    arrange(sleep_total)# ordering in ascending order

data_set1 %>%
    filter(order == "Primates", sleep_total > 10) %>%
    select(name, sleep_rem, sleep_cycle, sleep_total) %>%
    arrange(desc(sleep_total)) #Ordering in descending order

data_set1 %>%
    filter(order == "Primates", sleep_total > 10) %>%
    select(name, sleep_rem, sleep_cycle, sleep_total) %>%
    arrange(name) #can also be used to order non-numeric variables. 

data_set1 %>%
    filter(order == "Primates", sleep_total > 10) %>%
    select(name, sleep_rem, sleep_cycle, sleep_total) %>%
    arrange(name, sleep_total)# reorder rows based on information in multiple columns

#Creating New Columns
data_set1 %>%
    filter(order == "Primates", sleep_total > 10) %>%
    select(name, sleep_rem, sleep_cycle, sleep_total) %>%
    arrange(name) %>%
    mutate(sleep_total_min = sleep_total * 60) #we can create a new column


# --------------Statistics in R------------------

gtExtras::gt_plt_summary(data_set1)

t.test(data_set1$sleep_total, mu = 10)

t.test(data_set1$sleep_total, mu = 13, alternative = "greater", conf.level = .98)

wilcox.test(data_set1$sleep_total, mu = 13)

qqnorm(data_set1$sleep_total)
qqline(data_set1$sleep_total, lty = 2)

shapiro.test(data_set1$sleep_total)

atmos <- read.table("atmosphere.txt", header = TRUE)
str(atmos)
skim(atmos)

t.test(atmos$moisture ~ atmos$treatment)
t.test(atmos$moisture ~ atmos$treatment, var.equal = TRUE)
var.test(atmos$moisture ~ atmos$treatment)

pollution <- read.table("pollution.txt", header = TRUE)
str(pollution) 
t.test(pollution$down, pollution$up, paired = TRUE)
wilcox.test(pollution$down, pollution$up, paired = TRUE)

buy <- c(45, 71)  # creates a vector of positive outcomes
total <- c((45 + 35), (71 + 32))  # creates a vector of total numbers
prop.test(buy, total)  # perform the test (the binomial proportions test)
 
#A Chi-square contingency table. The simplest method is to convert the tabulated table into a 2 x 2 matrix using the matrix() function
buyers <- matrix(c(45, 35, 71, 32), nrow = 2)
colnames(buyers) <- c("before", "after")
rownames(buyers) <- c("buy", "notbuy")
buyers

chisq.test(buyers)#You can then perform a Chi-square test to test whether the number of cat owners buying the cat food is independent of the advertising campaign

# You can also use the chisq.test() function on raw (un-tabulated) data and to test for goodness of fit (see ?chisq.test for more details).'

data(trees) # Data is an in-built data set.
str(trees)

cor(trees$Height, trees$Volume)
cor(trees)
cor(trees, use = "complete.obs")
cor.test(trees$Height, trees$Volume)
cor.test(trees$Height, trees$Volume, method = "spearman")
cor.test(trees$Height, trees$Volume, method = "Kendall")
data()

data(package = .packages(all.available = TRUE)) #Use this to list the data sets in all *available* packages.

smoke <- read.table("smoking.txt", header = TRUE, sep = "\t",
    stringsAsFactors = TRUE)
str(smoke, vec.len = 2)
ggplot(mapping = aes(x = smoking, y = mortality), data = smoke) +
    geom_point()
smoke_lm <- lm(mortality ~ smoking, data = smoke)
smoke_lm
str(smoke_lm)
summary(smoke_lm)
anova(smoke_lm)

smoke_risk_lm <- lm(mortality ~ risk.group, data = smoke)
anova(smoke_risk_lm)
summary(smoke_risk_lm)

ggplot(mapping = aes(x = smoking, y = mortality), data = smoke) +
    geom_point() + geom_smooth(method = "lm", se = TRUE) #We can easily include the standard errors by specifying the se = TRUE argument.

# You can also do this with R’s base graphics. Note though that the fitted line extends beyond the data which is not great practice.
plot(smoke$smoking, smoke$mortality, xlab = "smoking rate", ylab = " mortality rate")
abline(smoke_lm, col = "red")

smoke_res <- resid(smoke_lm)
smoke_fit <- fitted(smoke_lm)
ggplot(mapping = aes(x = smoke_fit, y = smoke_res)) + geom_point() +
    geom_hline(yintercept = 0, colour = "red", linetype = "dashed")

# To check for normality of residuals we can use the Q-Q plot using the residuals stored in the smoke_res object
ggplot(mapping = aes(sample = smoke_res)) + stat_qq() + stat_qq_line()
qqnorm(smoke_res)
qqline(smoke_res)

# using the plot() function on the model object smoke_lm.
par(mfrow = c(2, 2))
plot(smoke_lm)
# You can also produce these diagnostic plots using ggplot by installing the package ggfortify and using the autoplot() function.
library(ggfortify)
autoplot(smoke_lm, which = 1:6, ncol = 2, label.size = 3)

smoke_lm2 <- update(smoke_lm, subset = -2) # the update()function examines the effect of removing one of these points on the parameter estimates
summary(smoke_lm2)#Let’s remove data point 2 (miners, mortality = 116 and smoking = 137) and store the results in a new object called smoke_lm2.
par(mfrow = c(2, 2))
plot(dffits(smoke_lm), type = "l")
plot(rstudent(smoke_lm))
matplot(dfbetas(smoke_lm), type = "l", col = "blue")
lines(sqrt(cooks.distance(smoke_lm)), lwd = 2)


```

```{r New Code for Functions in R Language}

#-------------------------Functions in R-----------------------

# just creating a dummy variable
df <- data.frame(a = rnorm(10), b = rnorm(10), c = rnorm(10),
    d = rnorm(10))
?rnorm
# normalising the variables i.e rescale each column to 0-1
# using min - max method.
df$a <- (df$a - min(df$a, na.rm = TRUE))/(max(df$a, na.rm = TRUE) -
    min(df$a, na.rm = TRUE))
df$b <- (df$b - min(df$b, na.rm = TRUE))/(max(df$b, na.rm = TRUE) -
    min(df$b, na.rm = TRUE))
df$c <- (df$c - min(df$c, na.rm = TRUE))/(max(df$c, na.rm = TRUE) -
    min(df$c, na.rm = TRUE))
df$d <- (df$d - min(df$d, na.rm = TRUE))/(max(df$d, na.rm = TRUE) -
    min(df$d, na.rm = TRUE))
df

# consider writing a function whenever you’ve copied and pasted a block of code more than twice (i.e. you now have three copies of the same code)
rescale_var <- function(var){
  minimum <- min(var, na.rm = TRUE)
  maximum <- max(var, na.rm = TRUE)
  var_new <- (var -minimum)/(maximum - minimum)
  return(var_new)
}

df$a <- rescale_var(df$a)
df$b <- rescale_var(df$b)
df$c <- rescale_var(df$c)
df$d <- rescale_var(df$d)

for (name in colnames(df)) {
    df$name <- rescale_var(df$name) 
} #you can use loop to ease your work

```

\`\``{r New Code for Functions in R} # BlChwhS Note that the`echo = FALSE\` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
